package ar.edu.unlu.blackjack.Modelo;

public enum Evento {
    JUGADA_REALIZADA,
    MANO_FINALIZADA,
    BLACKJACK,
    CRUPIER_BLACKJACK,
    CRUPIER_TIENE_AS,
    CRUPIER_BLACKJACK_Y_EMPATE,
    PERDIO_JUGADOR,
    GANADOR_JUGADOR,
    EMPATO_JUGADOR,
    JUGADOR_PAGO_SEGURO,
    JUGADOR_APOSTO,
    SALDO_AGREGADO,
    SALDO_RESTADO
}
