package ar.edu.unlu.blackjack.Modelo;

public enum Evento {
    ESPACIADOR_EN_CHAT,
    JUGADA_REALIZADA,
    MANO_FINALIZADA,
    BLACKJACK,
    CRUPIER_BLACKJACK,
    CRUPIER_TIENE_AS,
    CRUPIER_BLACKJACK_Y_EMPATE,
    PERDIO_JUGADOR,
    GANADOR_JUGADOR,
    EMPATO_JUGADOR,
    JUGADOR_PAGO_SEGURO,
    JUGADOR_APOSTO,
    SALDO_AGREGADO,
    SALDO_RESTADO,
    SALDO_AGREGADO_EMPATE,
    DEVUELTO_POR_SEGURO,
    PUNTUACION_FINAL_JUGADOR,
    PUNTUACION_FINAL_CRUPIER,
    ADJUDICAR_GANANCIA,
    ADJUDICAR_GANANCIA_BJ,
    APUESTA_AMBAS_MANOS,
    PUNTUACION_MANO1,
    PUNTUACION_MANO2

}
